export enum Colors {
  White = '#FFF',
  Black = '#000',
  PacificBlue = '#0089CD',
  Whisper = '#E5E5E5',
  SuvaGrey = '#8F8F8F',
  WhiteSmoke = '#F7F7F7',
  Charcoal = '#4A4A4A',
  Silver = '#C0C0C0',
  DeepSkyBlue = '#00A8F3',
  DarkJungleGreen = '#1C1F27',
}
export enum Screens {
  Home = 'Home',
  Product = 'Product',
  Search = 'Search',
  Root = 'Root',
  Profile = 'Profile',
  Orders = 'Orders',
  WishList = 'WishList',
  Cart = 'Cart',
  ModalScreen = 'ModalScreen',
  SignUp = 'SignUp',
  Login = 'Login',
  ForgotPassword = 'ForgotPassword',
}
